services:
  elasticsearch:
    image: elasticsearch:8.10.2ss
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      http.cors.enabled: "true"
      http.cors.allow-origin: "'*'"
      # Disable authentication in local development
      xpack.security.enabled: "false"
      xpack.security.enrollment.enabled: "false"
      # Disable default watermark, which can cause issues in local development:
      cluster.routing.allocation.disk.watermark.low: "2gb"
      cluster.routing.allocation.disk.watermark.high: "1gb"
      cluster.routing.allocation.disk.watermark.flood_stage: "500mb"
      cluster.info.update.interval: "1m"
    volumes:
      - ./elasticsearch/config/elasticsearch8.yml:/usr/share/elasticsearch/config/elasticsearch.yml
