name: next-drupal-starterkit
type: drupal
docroot: drupal/web
composer_root: drupal
nodejs_version: "20"
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
# This allows us to access the frontend app via https://frontend.ddev.site
# also check the traefik config in .ddev/traefik/config/frontend.yaml.
additional_hostnames:
  - frontend
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment:
  # This is the secret that is used by the backend to tell the frontend
  # to revalidate specific paths. The values need to match both in frontend
  # and backend.
  - DRUPAL_REVALIDATE_SECRET=revalidate_secret_not_secure_used_only_locally
  # This is the secret that is used by the frontend to issue calls to Drupal.
  # The values need to match both in frontend and backend.
  - DRUPAL_CLIENT_SECRET=drupal_client_secret_not_secure_used_only_locally
  # The client id, specified in the consumer on the Drupal side.
  - DRUPAL_CLIENT_ID=drupal-client-id
  # The client id for the unprivileged user, specified in the consumer on the Drupal side.
  - DRUPAL_CLIENT_VIEWER_ID=drupal-client-viewer-id
  - DRUPAL_CLIENT_VIEWER_SECRET=drupal_client_viewer_secret_not_secure_used_only_locally
  # URL OF THE FRONTEND SITE:
  # This needs to match the proxy value for the node service
  # so if you change it, remember to change it here as well.
  - WUNDER_NEXT_FRONTEND_URL=https://frontend.ddev.site
  - ENVIRONMENT_NAME=ddev
  - HASH_SALT=notsosecurehashnotsosecurehashnotsosecurehash
  - NEXT_PUBLIC_DRUPAL_BASE_URL=https://next-drupal-starterkit.ddev.site
  - NEXT_PUBLIC_FRONTEND_URL=https://frontend.ddev.site
    # Environment variables for next_auth:
  - AUTH_SECRET=nextauth_secret_not_secure_used_only_locally
  - AUTH_TRUST_HOST=true
  - AUTH_URL=https://frontend.ddev.site
   # Environment variables for redis
  - REDIS_HOST=redis
  - REDIS_PASS=redis
   # Environment variables for elasticsearch
  - ES_HOST=elasticsearch
  - SMTP_ADDRESS=localhost:1025

corepack_enable: false

hooks:
  post-start:
    - exec: "cd next && npm i"
    - exec-host: |
        # Run the Elasticsearch plugin setup script
        ddev exec -s elasticsearch /mnt/ddev_config/elasticsearch/elasticsearch-setup.sh
        # Check for the restart marker file
        if [ -f .ddev/elasticsearch/restart_needed ]; then
          echo "Elasticsearch plugins installed. Restarting elasticsearch container..."
          docker restart ddev-${DDEV_SITENAME}-elasticsearch
          rm .ddev/elasticsearch/restart_needed
        fi

web_extra_exposed_ports:
  - name: node-app
    container_port: 3000
    http_port: 3000
    https_port: 3001
